{
  "comments": [
    {
      "key": {
        "uuid": "88fb930a_536a47fc",
        "filename": "releasenotes/notes/fix-update-cloud-image-34c35922e841dae6.yaml",
        "patchSetId": 2
      },
      "lineNbr": 7,
      "author": {
        "id": 114
      },
      "writtenOn": "2020-04-21T01:48:56Z",
      "side": 1,
      "message": "drop \"the\"",
      "range": {
        "startLine": 7,
        "startChar": 60,
        "endLine": 7,
        "endChar": 63
      },
      "revId": "f99b1c0fc6410e4799569fd7cf27fbbe0a7fbb7e",
      "serverId": "f2a2391d-0403-4fa5-b183-4056999a8a09",
      "unresolved": true
    }
  ]
}